# Generated by Django 3.0.7 on 2020-07-20 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Avatar'),
        ),
    ]
