# Generated by Django 3.0.7 on 2020-07-02 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200702_1922'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_profile_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='room',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Room'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
