# Generated by Django 3.0.7 on 2020-07-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200708_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='image',
        ),
        migrations.AddField(
            model_name='avatar',
            name='static_image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
