# Generated by Django 3.0.7 on 2020-07-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200708_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='static_image_url',
        ),
        migrations.AddField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default=None, upload_to='avatars'),
            preserve_default=False,
        ),
    ]
