# Generated by Django 3.0.7 on 2020-08-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200729_1951'),
        ('users', '0005_auto_20200804_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_rooms',
            field=models.ManyToManyField(blank=True, related_name='user_rooms', to='rooms.Room'),
        ),
    ]
