# Generated by Django 3.0.7 on 2020-08-03 04:19

from django.db import migrations, transaction

def add_existing_room(apps, schema_editor):
    '''
    Migrate all existing room records to add to their rooms
    '''
    profile_model = apps.get_model('users', 'Profile')

    with transaction.atomic():    
        for profile in profile_model.objects.all():
            profile.user_rooms.add(profile.room)

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('users', '0006_profile_user_rooms'),
    ]

    operations = [
        migrations.RunPython(add_existing_room, reverse_code=migrations.RunPython.noop)
    ]
