# Generated by Django 3.0.7 on 2020-08-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_populate_user_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='room',
        ),
    ]
