# Generated by Django 3.1 on 2020-08-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='action_obj_contenttype',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='action_obj_id',
            new_name='object_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
