# Generated by Django 3.0.7 on 2020-07-10 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_avatar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(default=342, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Avatar'),
        ),
    ]
