# Generated by Django 3.1 on 2020-08-12 04:16

from django.db import migrations, models, transaction

def populate_user_rooms(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    Profile = apps.get_model('users', 'Profile')

    with transaction.atomic():

        for profile in Profile.objects.all():

            for room_uuid in profile.user_rooms_bak:
                room = Room.objects.get(uuid=room_uuid)
                profile.user_rooms.add(room)

            profile.save()
                




class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20200812_1214'),
        ('users', '0013_remove_profile_user_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_rooms',
            field=models.ManyToManyField(blank=True, related_name='user_rooms', to='rooms.Room'),
        ),
        migrations.RunPython(populate_user_rooms, reverse_code=migrations.RunPython.noop),
    ]
