# Generated by Django 3.0.7 on 2020-07-19 12:32

from django.db import migrations, models
import gdstorage.storage
import rooms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='raw_file',
            field=models.FileField(default=None, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='files', validators=[rooms.validators.limit_file_size, rooms.validators.allowed_file_type], verbose_name='File'),
            preserve_default=False,
        ),
    ]
