# Generated by Django 3.0.7 on 2020-07-29 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_auto_20200721_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='banned_users',
            field=models.ManyToManyField(editable=False, related_name='banned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='liked_by',
            field=models.ManyToManyField(editable=False, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='room',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rooms.Room'),
        ),
        migrations.AlterField(
            model_name='file',
            name='room',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rooms.Room'),
        ),
    ]
