# Generated by Django 3.0.7 on 2020-06-30 01:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200629_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='code',
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
