# Generated by Django 3.0.7 on 2020-08-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200729_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.RoomBackground'),
        ),
    ]
