# Generated by Django 3.0.7 on 2020-06-30 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200630_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='upload_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
