# Generated by Django 3.1 on 2020-08-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200805_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-posted_datetime']},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-posted_datetime']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='roombackground',
            options={'ordering': ['name']},
        ),
    ]
