# Generated by Django 3.0.7 on 2020-07-02 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0006_auto_20200702_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='room',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rooms.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
