# Generated by Django 3.1 on 2020-08-12 03:18

from django.db import migrations, models, transaction

def fill_id_autoincrement(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')

    with transaction.atomic():

        for i, room in enumerate(Room.objects.all()):
            room.id = i + 1
            room.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200812_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='id',
            field=models.PositiveIntegerField(null=True, verbose_name='ID'),
        ),
        migrations.RunPython(fill_id_autoincrement, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='ID'),
        ),
    ]
