# Generated by Django 3.0.7 on 2020-07-02 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage
import rooms.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0007_auto_20200702_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='raw_file',
            field=models.FileField(default=None, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='files', validators=[rooms.validators.limit_file_size]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
