# Generated by Django 3.1 on 2020-08-12 03:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200812_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='room',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='room',
            field=models.UUIDField(),
        ),
    ]
