# Generated by Django 3.0.7 on 2020-07-02 12:50

from django.db import migrations, models
import gdstorage.storage
import rooms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200702_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='raw_file',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='files', validators=[rooms.validators.limit_file_size, rooms.validators.allowed_file_type], verbose_name='File'),
        ),
    ]
