# Generated by Django 3.0.7 on 2020-07-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20200702_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='raw_file',
        ),
    ]
