# Generated by Django 3.1 on 2020-08-12 04:06

import django.contrib.postgres.fields
from django.db import migrations, models, transaction
import uuid

def populate_banned_users(apps, schema_editor):

    Room = apps.get_model('rooms', 'Room')

    with transaction.atomic():

        for room in Room.objects.all():

            banned_users = []
            for banned_user in room.banned_users.all():
                banned_users.append(banned_user.pk)
            room.banned_users_bak = banned_users
            room.save()
            


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20200812_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='banned_users_bak',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
        migrations.RunPython(populate_banned_users, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name='room', name='banned_users'),
        
    ]
