# Generated by Django 3.0.7 on 2020-07-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20200704_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
