# Generated by Django 3.1 on 2020-08-12 04:22

from django.conf import settings
from django.db import migrations, models, transaction

def populate_banned_users(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    Profile = apps.get_model('users', 'Profile')

    with transaction.atomic():

        for room in Room.objects.all():

            for banned_user_id in room.banned_users_bak:
                user = Profile.objects.get(user__id=banned_user_id)
                room.banned_users.add(user)

            room.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0011_auto_20200812_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='banned_users',
            field=models.ManyToManyField(editable=False, related_name='banned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_banned_users, reverse_code=migrations.RunPython.noop),
    ]
