# Generated by Django 3.1 on 2020-08-12 04:32

from django.db import migrations, models, transaction
import django.db.models.deletion

def populate_file_room(apps, schema_editor):
    File = apps.get_model('rooms', 'File')
    Room = apps.get_model('rooms', 'Room')

    with transaction.atomic():

        # Get old room uuid -> Get room based on uuid -> Set File's room to room_new
        for file_obj in File.objects.all():
            room = Room.objects.get(uuid=file_obj.room) # obj.room here is UUID, still not INT
            file_obj.room_new = room
            file_obj.save()

def populate_announcement_room(apps, schema_editor):
    Announcement = apps.get_model('rooms', 'Announcement')
    Room = apps.get_model('rooms', 'Room')

    with transaction.atomic():

        # Get old room uuid -> Get room based on uuid -> Set Announcement's room to room_new
        for announcement_obj in Announcement.objects.all():
            room = Room.objects.get(uuid=announcement_obj.room) # obj.room here is UUID, still not INT
            announcement_obj.room_new = room
            announcement_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_remove_room_banned_users_bak'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='room_new',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='rooms.room', null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='room_new',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='rooms.room', null=True),
            preserve_default=False,
        ),
        migrations.RunPython(populate_file_room, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(populate_announcement_room, reverse_code=migrations.RunPython.noop),
    ]
