# Generated by Django 3.0.7 on 2020-07-04 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_auto_20200704_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='upload_datetime',
            new_name='posted_datetime',
        ),
        migrations.AddField(
            model_name='announcement',
            name='posted_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
