# Generated by Django 3.0.7 on 2020-07-06 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0014_auto_20200704_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
