# Generated by Django 3.1 on 2020-08-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_auto_20200812_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='room',
        ),
        migrations.RemoveField(
            model_name='file',
            name='room',
        ),
    ]
