# Generated by Django 3.1 on 2020-08-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_auto_20200812_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='room_new',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='room_new',
            new_name='room',
        ),
    ]
