# Generated by Django 3.0.7 on 2020-07-10 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='executed_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
